
export enum Region {
  ILE_DE_FRANCE = 11,
  CENTRE_VAL_DE_LOIRE = 24,
  BOURGOGNE = 27,
  NORMANDIE = 28,
  HAUT_DE_FRANCE = 32,
  GRAND_EST = 44,
  PAYS_DE_LA_LOIRE = 52,
  BRETAGNE = 53,
  NOUVELLE_ACQUITAINE = 75,
  OCCITANIE = 76,
  AUVERGNE = 84,
  PACA = 93,
  GRANDE_COURONNE = 12,
  PETITE_COURONNE = 12
}
